### ISSUE TITLE
[InsertTimestamps] Still broken as of latest update

### ISSUE THREAD

**Issue by QuentinMcCarthy** [Vendicated/BetterDiscordPlugins#6]
Cannot read properties of undefined (reading 'default). Plugin could not be started.

Just updated the plugin today, version 1.0.3

**Comment by alexzander700** [comment]
![image](https://github.com/Vendicated/BetterDiscordPlugins/assets/51793351/f3001c04-62f9-4192-9442-d53d87e6cd4a)
No clue on how to help with this issue as there's no error logs that I can find.

**Comment by Nox13last** [comment]
For future reference, you can open the Developer Console on Discord with CTRL+Shift+I. You might have to do it while it's logging in (before the channel list comes up).
```
72243.bf730b4ff896b85f9c2c.js:1 [PluginManager] InsertTimestamps v1.0.3 could not be started. TypeError: Cannot read properties of undefined (reading 'default')
    at Object.start (InsertTimestamps.plugin.js:175:40)
    at A.startPlugin (renderer.js:5:35363)
    at A.startAddon (renderer.js:5:35156)
    at A.enableAddon (renderer.js:5:8634)
    at A.toggleAddon (renderer.js:5:8891)
    at A.togglePlugin (renderer.js:5:32444)
    at renderer.js:5:87082
    at renderer.js:5:79852
    at Object.eN (81611.bc94e2573748b039d882.js:1:751091)
    at eB (81611.bc94e2573748b039d882.js:1:751245)
    at 81611.bc94e2573748b039d882.js:1:769554
    at re (81611.bc94e2573748b039d882.js:1:769653)
    at rt (81611.bc94e2573748b039d882.js:1:770067)
    at 81611.bc94e2573748b039d882.js:1:775529
    at sE (81611.bc94e2573748b039d882.js:1:832586)
    at eC (81611.bc94e2573748b039d882.js:1:750229)
    at rs (81611.bc94e2573748b039d882.js:1:771358)
    at tN (81611.bc94e2573748b039d882.js:1:757026)
    at tF (81611.bc94e2573748b039d882.js:1:756810)
e.<computed> @ 72243.bf730b4ff896b85f9c2c.js:1
stacktrace @ renderer.js:5
startPlugin @ renderer.js:5
startAddon @ renderer.js:5
enableAddon @ renderer.js:5
toggleAddon @ renderer.js:5
togglePlugin @ renderer.js:5
(anonymous) @ renderer.js:5
(anonymous) @ renderer.js:5
eN @ 81611.bc94e2573748b039d882.js:1
eB @ 81611.bc94e2573748b039d882.js:1
(anonymous) @ 81611.bc94e2573748b039d882.js:1
re @ 81611.bc94e2573748b039d882.js:1
rt @ 81611.bc94e2573748b039d882.js:1
(anonymous) @ 81611.bc94e2573748b039d882.js:1
sE @ 81611.bc94e2573748b039d882.js:1
eC @ 81611.bc94e2573748b039d882.js:1
rs @ 81611.bc94e2573748b039d882.js:1
tN @ 81611.bc94e2573748b039d882.js:1
tF @ 81611.bc94e2573748b039d882.js:1
```

**Comment by walbjorn** [comment]
aye broken for me too
